[project]
name = "hype-meter"
version = "0.9"
description = "The hype meter app"
readme = "README.md"
requires-python = ">=3.14, <3.15"
dependencies = [
    "django~=6.0.1",
    "django-environ>=0.12.0",
    "psycopg-binary>=3.3.2",
    "python-json-logger>=4.0.0",
    "requests>=2.32.5",
]

[dependency-groups]
dev = [
    "freezegun>=1.5.5",
    "model-bakery>=1.23.2",
    "pytest>=9.0.1,<10",
    "pytest-cov>=7.0.0",
    "pytest-django>=4.11.1",
    "pytest-mock>=3.15.1",
    "ruff==0.14.14",
]

[tool.pytest.ini_options]
minversion = "6.0"
addopts = "-ra -q --cov=apps --cov-report=term-missing"
DJANGO_SETTINGS_MODULE = "config.settings"

[tool.coverage.run]
omit = ["*migrations*", "*tests*", "config/*"]
