# Generated by Django 6.0.1 on 2026-02-01 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Record creation date')),
                ('updated_at', models.DateField(auto_now_add=True, verbose_name='Last modification')),
                ('name', models.CharField(db_index=True, help_text='The normalized search term.', max_length=255, unique=True, verbose_name='Keyword')),
                ('score', models.PositiveIntegerField(default=0, help_text='Weighted average score (0-100).', verbose_name='Hype scoring value')),
                ('history_data', models.JSONField(default=dict, help_text='Stores the 7-day pulse data for charting.', verbose_name='History data')),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
                'ordering': ['-score'],
            },
        ),
    ]
